model_list:
  # --- #1 ---
  - model_name: gemini-3-flash-preview
    litellm_params:
      model_id: google-account-1
      model: gemini/gemini-3-flash-preview
      api_key: "os.environ/GEMINI_API_KEY"

  - model_name: kimi-k2.5
    litellm_params:
      model_id: openrouter-account-1
      model: openrouter/moonshotai/kimi-k2.5
      api_key: "os.environ/OPENROUTER_API_KEY"

  - model_name: minimax-m2.5
    litellm_params:
      model_id: openrouter-account-2
      model: openrouter/minimax/minimax-m2.5
      api_key: "os.environ/OPENROUTER_API_KEY"

litellm_settings:
  drop_params: true
  set_verbose: false
  callbacks: ["langfuse_otel","prometheus"]